name: Deploy CDK Stacks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Detect changes
        id: changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^apps/frontend/'; then
            echo "frontend=true" >> $GITHUB_ENV
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^apps/backend/'; then
            echo "backend=true" >> $GITHUB_ENV
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^infra/'; then
            echo "infra=true" >> $GITHUB_ENV
          fi

      - name: Deploy Frontend Stack
        if: env.frontend == 'true' || env.infra == 'true'
        run: npx cdk deploy FrontendStack --require-approval never

      - name: Deploy Backend Stack
        if: env.backend == 'true' || env.infra == 'true'
        run: npx cdk deploy BackendStack --require-approval never
